/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#0d1a38",
        "secondary-container": "#cad6fd",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#002022",
        "primary-fixed": "#d6e3ff",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#00929b",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "tertiary-fixed": "#7df4ff",
        "surface-container": "#eceef0",
        "on-error": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#004f54",
        "secondary": "#525e7f",
        "on-surface-variant": "#44474d",
        "primary-container": "#0d1c32",
        "on-primary-container": "#76849f",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "outline-variant": "#c5c6cd",
        "on-primary-fixed-variant": "#39475f",
        "on-primary-fixed": "#0d1c32",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3a4666",
        "inverse-primary": "#b9c7e4",
        "tertiary-container": "#002022",
        "surface-variant": "#e0e3e5",
        "on-background": "#191c1e",
        "surface": "#f7f9fb",
        "outline": "#75777e",
        "on-secondary-container": "#515d7e",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed": "#dae2ff",
        "surface-tint": "#515f78",
        "background": "#f7f9fb",
        "primary-fixed-dim": "#b9c7e4",
        "tertiary-fixed-dim": "#00dbe9",
        "tertiary": "#000000",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed-dim": "#bac6ec",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        "headline": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body": ["var(--font-inter)", "Inter", "sans-serif"],
        "label": ["var(--font-inter)", "Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
